# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'tkinter.constants',
        'PIL',
        'PIL._tkinter_finder',
        'docx',
        'openpyxl',
        'pptx',
        'olefile',
        'chardet',
        'pdfplumber',
        'PyPDF2',
        'PyPDF2.generic',
        'PyPDF2.filters',
        'PyPDF2.utils',
        'PyPDF2._crypt',
        'PyPDF2._cmap',
        'PyPDF2._page',
        'PyPDF2._reader',
        'PyPDF2._utils',
        'PyPDF2._writer',
        'PyPDF2.constants',
        'PyPDF2.errors',
        'pdfplumber.pdfplumber',
        'pdfplumber.page',
        'pdfplumber.utils',
        'pdfplumber.display',
        'pdfplumber.geom',
        'pdfplumber.table',
        'pdfplumber.pdf',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    cipher=block_cipher,
    win_private_assemblies=False,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='文档管家',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
